version: 2

models:
  
  - name: rpt_player_performance_by_season_home
    description: Basic player stats for home game for each player

  - name: rpt_player_performance_by_season_away
    description: Basic player stats for away game for each player

