name: 'nhl_stats'
version: '1.0.0'
config-version: 2

# This setting configures which 'profile' dbt uses for this project.  See profiles.yml sample file in this folder
profile: 'nhl_stats'

source-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
data-paths: ['data']
macro-paths: ['macros']
snapshots: ['snapshots']

target-path: 'target' # directory to store compiled SQL files
clean-targets:        # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_modules'

# variables